name: Deploy to Azure Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
          cache-dependency-path: TaskFlow/frontend/package-lock.json

      - name: Install dependencies
        run: |
          cd TaskFlow/frontend
          npm ci

      - name: Build React app
        run: |
          cd TaskFlow/frontend
          npm run build

      - name: Create deployment package
        run: |
          cd TaskFlow/frontend
          # Copy server.js and package.json to build folder
          cp server.js build/
          cp package.json build/
          cp package-lock.json build/
          # Create a minimal package.json for production
          cd build
          cat > package.json << 'EOF'
          {
            "name": "taskflow-frontend",
            "version": "1.0.2",
            "private": true,
            "dependencies": {
              "express": "^4.21.2"
            },
            "scripts": {
              "start": "node server.js"
            }
          }
          EOF

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "taskflow-webapp-legion"
          slot-name: "production"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: TaskFlow/frontend/build
