        # .github/workflows/backend-ci.yml
        name: Backend CI Pipeline

        # This pipeline runs on any push or pull request to the develop branch
        on:
          push:
            branches: [ develop ]
          pull_request:
            branches: [ develop ]

        jobs:
          build-and-test:
            # The type of runner that the job will run on
            runs-on: ubuntu-latest

            # We only care about the backend for this job
            defaults:
              run:
                working-directory: ./backend

            strategy:
              matrix:
                node-version: [18.x] # Use a recent LTS version of Node.js

            steps:
            # Step 1: Check out the repository code
            - name: Checkout repository
              uses: actions/checkout@v3

            # Step 2: Setup Node.js environment
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'
                cache-dependency-path: backend/package-lock.json

            # Step 3: Install dependencies securely
            - name: Install Dependencies
              run: npm ci

            # Step 4: Run the linter to check code style
            - name: Run Linter
              run: npx eslint . --ext .js

            # Step 5: Run unit tests
            # Note: This requires a running database. For a real CI pipeline,
            # you would use Docker to spin up a temporary Postgres database.
            # For now, we will skip tests that require a DB in CI if they fail.
            - name: Run Tests
              run: npm test
        