repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: backend-lint
        name: Backend ESLint
        entry: bash -c 'cd TaskFlow/backend && npm run lint'
        language: system
        files: ^TaskFlow/backend/.*\.js$
        pass_filenames: false

      - id: frontend-lint
        name: Frontend ESLint
        entry: bash -c 'cd TaskFlow/frontend && npm run lint'
        language: system
        files: ^TaskFlow/frontend/.*\.(js|jsx)$
        pass_filenames: false

      - id: backend-tests
        name: Backend Tests
        entry: bash -c 'cd TaskFlow/backend && npm test'
        language: system
        files: ^TaskFlow/backend/.*\.js$
        pass_filenames: false

      - id: frontend-tests
        name: Frontend Tests
        entry: bash -c 'cd TaskFlow/frontend && npm test -- --watchAll=false'
        language: system
        files: ^TaskFlow/frontend/.*\.(js|jsx)$
        pass_filenames: false