version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: taskflow
      POSTGRES_PASSWORD: taskflowpass
      POSTGRES_DB: taskflow
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    environment:
      DATABASE_URL: postgres://taskflow:taskflowpass@db:5432/taskflow
      NODE_ENV: production
      PORT: 5000
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
