# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - taskflow-webapp-Legion

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          # Add a working-directory here for setup-node if it's causing issues,
          # but typically it's for the 'run' commands.
          # working-directory: ./frontend # Consider adding this if the below doesn't work

      - name: Change to frontend directory and run npm commands
        run: |
          cd frontend # <--- ADDED: Explicitly change directory here
          npm install
          npm run build --if-present
          npm run test --if-present
        # Removed working-directory from here, as 'cd frontend' handles it explicitly
        # working-directory: ./frontend # <--- REMOVED this line

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # CHANGED: This now uploads only the built output of your Next.js app (the .next folder)
          # assuming your build output is inside the 'frontend/.next' directory.
          path: ./frontend/.next

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B573F7E44E5349029F971BB091EA22AB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1ECAF2DD16BA45EFAE4ACBDA3BF7EA9C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8D0A92E3CE4E45978662BA8C8AD8A5C6 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'taskflow-webapp-Legion'
          slot-name: 'Production'
          # This now correctly points to the root of the downloaded artifact,
          # which will be the contents of your .next folder.
          package: .
